// =================================
// Copyright (c) 2024 Seppo Laakko
// Distributed under the MIT license
// =================================

#ifndef CMRT_WIN_API_INCLUDED
#define CMRT_WIN_API_INCLUDED
#include <stdint.h>

extern "C" void WinSetInstance();
extern "C" void WinInit(void* messageProcessorFunctionAddress, void* keyPreviewFunctionAddress);
extern "C" int WinRun();
extern "C" int WinApplicationMessageLoop();
extern "C" void WinRunModal();
extern "C" void* WinGetForegroundWindow();
extern "C" bool WinEnableWindow(void* windowHandle, bool enable);
extern "C" int WinDialogWindowMessageLoop(void* windowHandle, void* parentWindowHandle, void* getDialogResultFunc, void* keyPreviewFunc, void* dialogWindowPtr);
extern "C" void* WinSubClassCommandWndProc(void* windowHandle);
extern "C" void WinRestoreOriginalWndProc(void* windowHandle, void* originalWndProc);
extern "C" void WinDone();
extern "C" int WinShowMessageBox(const char* text, const char* caption);
extern "C" int WinShowMessageBoxWithType(const char* text, const char* caption, void* ownerWindowHandle, uint32_t type);
extern "C" void* WinCreateEvent();
extern "C" bool WinSetEvent(void* eventHandle);
extern "C" bool WinResetEvent(void* eventHandle);
extern "C" bool WinWaitEvent(void* eventHandle);
extern "C" bool WinCloseHandle(void* handle);
extern "C" bool WinKeyPressed(int keyCode);
extern "C" int32_t WinWaitForMultipleObjects(uint32_t count, void** handles);
extern "C" void* WinFindFirstChangeNotification(const char* directoryPath);
extern "C" bool WinFindNextChangeNotification(void* handle);
extern "C" bool WinFindCloseChangeNotification(void* handle);
extern "C" bool WinShellExecute(const char* filePath, int64_t& errorCode);
extern "C" uint16_t WinRegisterWindowClass(const char* windowClassName, uint32_t style, int backgroundColor);
extern "C" bool WinMessageBeep(uint32_t messageBeepType);
extern "C" void* WinCreateWindowByClassAtom(uint16_t windowClass, const char* windowName, int64_t style, int64_t exStyle, int x, int y, int w, int h, void* parentHandle);
extern "C" void* WinCreateWindowByClassName(const char* windowClass, const char* windowName, int64_t style, int64_t exStyle, int x, int y, int w, int h, void* parentHandle);
extern "C" void WinDestroyWindow(void* windowHandle);
extern "C" void WinPostQuitMessage(int exitCode);
extern "C" bool WinPostMessage(void* windowHandle, uint32_t msg, uint64_t wparam, int64_t lparam);
extern "C" int64_t WinSendMessage(void* windowHandle, uint32_t msg, uint64_t wparam, int64_t lparam);
extern "C" bool WinShowWindow(void* windowHandle, int commandShow);
extern "C" bool WinUpdateWindow(void* windowHandle);
extern "C" bool WinMoveWindow(void* windowHandle, int x, int y, int w, int h, bool repaint);
extern "C" bool WinGetClientRect(void* windowHandle, void* rect);
extern "C" bool WinGetWindowRect(void* windowHandle, void* rect);
extern "C" bool WinClientToScreen(void* windowHandle, void* point);
extern "C" bool WinScreenToClient(void* windowHandle, void* point);
extern "C" bool WinPtInRect(void* rect, void* point);
extern "C" bool WinSetWindowText(void* windowHandle, const char* text);
extern "C" int WinGetWindowTextLength(void* windowHandle);
extern "C" int WinGetWindowText(void* windowHandle, char16_t* textBuffer, int maxCount);
extern "C" void* WinGetDC(void* windowHandle);
extern "C" int WinReleaseHDC(void* windowHandle, void* hdc);
extern "C" bool WinTrackMouseEvent(void* windowHandle, uint32_t flags, uint32_t hoverTimeMs);
extern "C" void* WinSetParent(void* childWindowHandle, void* parentWindowHandle);
extern "C" bool WinInvalidateRect(void* windowHandle, void* rect, bool eraseBackground);
extern "C" void* WinBeginPaint(void* windowHandle, void*& paintStruct);
extern "C" void WinEndPaint(void* windowHandle, void* paintStruct);
extern "C" void WinGetClipRect(void* paintStruct, int& x, int& y, int& w, int& h);
extern "C" void WinGetSysColor(int index, uint8_t& red, uint8_t& green, uint8_t& blue);
extern "C" bool WinSetBkColor(void* hdc, uint8_t red, uint8_t green, uint8_t blue);
extern "C" void WinGetMessagePos(int32_t& x, int32_t& y);
extern "C" void* WinGetFocus();
extern "C" void* WinSetFocus(void* windowHandle);
extern "C" void* WinGetTopWindow(void* windowHandle);
extern "C" bool WinBringWindowToTop(void* windowHandle);
extern "C" bool WinSetWindowPos(void* windowHandle, void* insertAfterWindowHandle, int x, int y, int cx, int cy, uint32_t flags);
extern "C" bool WinGetOpenFileName(void* windowHandle, const char16_t* filter, const char16_t* initialDirectory, char16_t* fileNameBuffer, uint32_t fileNameBufferSize,
    uint32_t flags, const char16_t* defaultExtension);
extern "C" bool WinGetSaveFileName(void* windowHandle, const char16_t* filter, const char16_t* initialDirectory, char16_t* fileNameBuffer, uint32_t fileNameBufferSize,
    uint32_t flags, const char16_t* defaultExtension);
extern "C" uint32_t WinCommDlgExtendedError();
extern "C" void* WinLoadImage(const char* name, uint32_t type, int32_t cx, int32_t cy);
extern "C" void* WinLoadStandardCursor(int cursorId);
extern "C" void* WinLoadCursor(const char* cursorName);
extern "C" void* WinGetCursor();
extern "C" void* WinSetCursor(void* cursorHandle);
extern "C" bool WinDestroyCursor(void* cursorHandle);
extern "C" void* WinLoadStandardIcon(int iconId);
extern "C" void* WinLoadIcon(const char* iconName);
extern "C" bool WinDestroyIcon(void* iconHandle);
extern "C" void* WinLoadStandardBitmap(int bitmapId);
extern "C" void* WinLoadBitmap(const char* bitmapName);
extern "C" bool WinDestroyBitmap(void* bitmapHandle);
extern "C" bool WinDeleteObject(void* handle);
extern "C" int WinGetSystemMetrics(int index);
extern "C" void* WinSetCapture(void* windowHandle);
extern "C" bool WinReleaseCapture();
extern "C" int64_t WinGetClassLong(void* windowHandle, int index);
extern "C" int64_t WinSetClassLong(void* windowHandle, int index, int64_t value);
extern "C" int64_t WinGetWindowLong(void* windowHandle, int index);
extern "C" bool WinSetWindowLong(void* windowHandle, int index, int64_t newValue);
extern "C" bool WinScrollWindow(void* windowHandle, int xAmount, int yAmount, int clientLocX, int clientLocY, int clientSizeW, int clientSizeH,
    int clipLocX, int clipLocY, int clipSizeW, int clipSizeH);
extern "C" bool WinScrollWindowEx(void* windowHandle, int dx, int dy, int clientLocX, int clientLocY, int clientSizeW, int clientSizeH,
    int clipLocX, int clipLocY, int clipSizeW, int clipSizeH, int x1, int y1, int x2, int y2);
extern "C" bool WinGetScrollInfo(void* windowHandle, int nBar, uint32_t& nPage, int32_t& nPos, int32_t& nMin, int32_t& nMax, int32_t& nTrackPos);
extern "C" int WinSetScrollInfo(void* windowHandle, int nBar, uint32_t fMask, bool redraw, uint32_t nPage, int32_t nPos, int32_t nMin, int32_t nMax);
extern "C" int WinGetScrollPos(void* windowHandle, int nBar);
extern "C" bool WinShowScrollBar(void* windowHandle, int nBar, bool show);
extern "C" bool WinCreateCaret(void* windowHandle, void* bitmapHandle, int width, int height);
extern "C" bool WinDestroyCaret();
extern "C" bool WinShowCaret(void* windowHandle);
extern "C" bool WinHideCaret(void* windowHandle);
extern "C" bool WinGetCaretPos(int& x, int& y);
extern "C" bool WinSetCaretPos(int x, int y);
extern "C" bool WinSetTimer(void* windowHandle, uint32_t timerId, uint32_t elapse);
extern "C" bool WinKillTimer(void* windowHandle, uint32_t timerId);
extern "C" bool WinRegOpenCurrentUser(void** result);
extern "C" bool WinRegCloseKey(void* key);
extern "C" bool WinRegGetDWordValue(void* key, const char* subKey, const char* valueName, uint32_t& value);
extern "C" uint32_t WinRegisterClipboardFormat(const char* formatName);
extern "C" bool WinOpenClipboard(void* windowHandle);
extern "C" bool WinCloseClipboard();
extern "C" bool WinEmptyClipboard();
extern "C" void* WinSetClipboardData(uint32_t format, void* mem);
extern "C" void* WinGetClipboardData(uint32_t format);
extern "C" bool WinIsClipboardFormatAvailable(uint32_t format);
extern "C" bool WinAddClipboardFormatListener(void* windowHandle);
extern "C" bool WinRemoveClipboardFormatListener(void* windowHandle);
extern "C" void* WinGlobalAlloc(uint32_t flags, uint64_t size);
extern "C" void* WinGlobalLock(void* memHandle);
extern "C" bool WinGlobalUnlock(void* memHandle);
extern "C" void* WinGlobalFree(void* memHandle);
extern "C" uint64_t WinGlobalSize(void* memHandle);
extern "C" bool WinGetCursorPos(int& x, int& y);
extern "C" bool WinGetFolder(void* windowHandle, const char16_t* defaultDirectory, char16_t* folderNameBuffer, uint32_t folderNameBufferSize);
extern "C" int WinGetLogicalDrives();
extern "C" void* WinCreateGraphics(void* hdc);
extern "C" void WinDeleteGraphics(void* nativeGraphics);
extern "C" void* WinCreateGraphicsFromWindowHandle(void* hwnd);
extern "C" void* WinCreateGraphicsFromImage(void* image);
extern "C" int WinGraphicsGetLastStatus(void* graphics);
extern "C" int WinGraphicsFontGetLastStatus(void* font);
extern "C" void* WinGraphicsGetHDC(void* nativeGraphics);
extern "C" void* WinGraphicsCreatePen(uint8_t alpha, uint8_t red, uint8_t green, uint8_t blue, float width);
extern "C" void WinGraphicsDeletePen(void* pen);
extern "C" void* WinGraphicsClonePen(void* pen);
extern "C" int WinGraphicsPenGetLastStatus(void* pen);
extern "C" int WinGraphicsPenGetAlignment(void* pen);
extern "C" int WinGraphicsPenSetAlignment(void* pen, int alignment);
extern "C" void* WinGraphicsPenGetBrush(void* pen);
extern "C" int WinGraphicsPenSetBrush(void* pen, void* brush);
extern "C" int WinGraphicsPenGetColor(void* pen, uint8_t& alpha, uint8_t& red, uint8_t& green, uint8_t& blue);
extern "C" int WinGraphicsPenSetColor(void* pen, uint8_t alpha, uint8_t red, uint8_t green, uint8_t blue);
extern "C" int WinGraphicsPenGetStartCap(void* pen);
extern "C" int WinGraphicsPenSetStartCap(void* pen, int startCap);
extern "C" int WinGraphicsPenGetEndCap(void* pen);
extern "C" int WinGraphicsPenSetEndCap(void* pen, int endCap);
extern "C" int WinGraphicsPenGetDashCap(void* pen);
extern "C" int WinGraphicsPenSetDashCap(void* pen, int dashCap);
extern "C" float WinGraphicsPenGetDashOffset(void* pen);
extern "C" int WinGraphicsPenSetDashOffset(void* pen, float dashOffset);
extern "C" int WinGraphicsPenGetDashStyle(void* pen);
extern "C" int WinGraphicsPenSetDashStyle(void* pen, int dashStyle);
extern "C" int WinGraphicsPenGetLineJoin(void* pen);
extern "C" int WinGraphicsPenSetLineJoin(void* pen, int lineJoin);
extern "C" void* WinGraphicsCreateSolidBrush(uint8_t alpha, uint8_t red, uint8_t green, uint8_t blue);
extern "C" void* WinGraphicsCloneSolidBrush(void* solidBrush);
extern "C" void WinGraphicsDeleteSolidBrush(void* solidBrush);
extern "C" int WinGraphicsBrushGetLastStatus(void* brush);
extern "C" void* WinGraphicsCreateEmptyFontFamily();
extern "C" void* WinGraphicsCreateFontFamily(const char* familyName);
extern "C" void* WinGraphicsCloneFontFamily(void* fontFamily);
extern "C" void WinGraphicsDeleteFontFamily(void* fontFamily);
extern "C" int WinGraphicsGetFontFamilyName(void* fontFamily, void*& str);
extern "C" const void* WinGraphicsGetGenericMonospaceFontFamily();
extern "C" const void* WinGraphicsGetGenericSansSerifFontFamily();
extern "C" const void* WinGraphicsGetGenericSerifFontFamily();
extern "C" int WinGraphicsFontFamilyGetLastStatus(void* fontFamily);
extern "C" void* WinGraphicsCreateFont(const void* fontFamily, float emSize, int style, int unit);
extern "C" void* WinGraphicsCreateFontFromHFont(void* hdc, void* hfont);
extern "C" void* WinGraphicsCloneFont(void* font);
extern "C" void WinGraphicsDeleteFont(void* font);
extern "C" int WinGraphicsGetFontFamily(void* font, void* fontFamily);
extern "C" float WinGraphicsGetFontSize(void* font);
extern "C" float WinGraphicsGetFontHeight(void* font, const void* graphics);
extern "C" int WinGraphicsGetFontStyle(void* font);
extern "C" int WinGraphicsFontToHFont(void* font, void* graphics, void*& hfont);
extern "C" void* WinGraphicsCreateDefaultStringFormat();
extern "C" const void* WinGraphicsGetGenericDefaultStringFormat();
extern "C" const void* WinGraphicsGetGenericTypographicStringFormat();
extern "C" void* WinGraphicsCreateStringFormat(int formatFlags, uint16_t languageId);
extern "C" void* WinGraphicsCloneStringFormat(void* stringFormat);
extern "C" void WinGraphicsDeleteStringFormat(void* stringFormat);
extern "C" int WinGraphicsStringFormatGetLastStatus(void* stringFormat);
extern "C" int WinGraphicsStringFormatSetAlignment(void* stringFormat, int alignment);
extern "C" int WinGraphicsStringFormatSetLineAlignment(void* stringFormat, int alignment);
extern "C" int WinGraphicsStringFormatSetHotKeyPrefix(void* stringFormat, int hotKeyPrefix);
extern "C" int WinGraphicsDrawLine(void* graphics, void* pen, int startX, int startY, int endX, int endY);
extern "C" int WinGraphicsDrawLineF(void* graphics, void* pen, float startX, float startY, float endX, float endY);
extern "C" int WinGraphicsDrawLines(void* graphics, void* pen, int count, void* points);
extern "C" int WinGraphicsDrawLinesF(void* graphics, void* pen, int count, void* points);
extern "C" int WinGraphicsDrawString(void* graphics, const char* str, void* font, float x, float y, void* brush);
extern "C" int WinGraphicsDrawStringFormatPoint(void* graphics, const char* str, void* font, float x, float y, void* format, void* brush);
extern "C" int WinGraphicsDrawStringFormatRect(void* graphics, const char* str, void* font, float x, float y, float w, float h, void* format, void* brush);
extern "C" int WinGraphicsMeasureStringFormatSize(void* graphics, const char* str, void* font, float w, float h, void* format,
    float& outSizeW, float& outSizeH, int* codePointsFitted, int* linesFilled);
extern "C" int WinGraphicsMeasureStringFormatRect(void* graphics, const char* str, void* font, float x, float y, float w, float h, void* format,
    float& outX, float& outY, float& outW, float& outH, int* codePointsFitted, int* linesFilled);
extern "C" int WinGraphicsMeasureStringFormatPoint(void* graphics, const char* str, void* font, float x, float y, void* format,
    float& outX, float& outY, float& outW, float& outH);
extern "C" int WinGraphicsGetTextRenderingHint(void* graphics);
extern "C" int WinGraphicsSetTextRenderingHint(void* graphics, int textRenderingHint);
extern "C" int WinGraphicsClear(void* graphics, uint8_t alpha, uint8_t red, uint8_t green, uint8_t blue);
extern "C" int WinGraphicsDrawRectangle(void* graphics, void* pen, int x, int y, int w, int h);
extern "C" int WinGraphicsDrawRectangleF(void* graphics, void* pen, float x, float y, float w, float h);
extern "C" int WinGraphicsFillRectangle(void* graphics, void* brush, int x, int y, int w, int h);
extern "C" int WinGraphicsFillRectangleF(void* graphics, void* brush, float x, float y, float w, float h);
extern "C" int WinGraphicsFillPolygon(void* graphics, void* brush, int count, void* points);
extern "C" int WinGraphicsFillPolygonF(void* graphics, void* brush, int count, void* points);
extern "C" int WinGraphicsDrawArc(void* graphics, void* pen, float x, float y, float w, float h, float startAngle, float sweepAngle);
extern "C" int WinGraphicsDrawEllipse(void* graphics, void* pen, float x, float y, float w, float h);
extern "C" int WinGraphicsFillEllipse(void* graphics, void* brush, float x, float y, float w, float h);
extern "C" void* WinGraphicsCreateRegion();
extern "C" void* WinGraphicsCloneRegion(void* region);
extern "C" void WinGraphicsDeleteRegion(void* region);
extern "C" int WinGraphicsRegionGetLastStatus(void* region);
extern "C" int WinGraphicsGetClip(void* graphics, void* region);
extern "C" int WinGraphicsSetClipRect(void* graphics, int x, int y, int w, int h, int combineMode);
extern "C" int WinGraphicsSetClipRegion(void* graphics, void* region);
extern "C" void* WinGraphicsCreateImage(const char* fileName, bool useEmbeddedColorManagement);
extern "C" int WinGraphicsImageGetLastStatus(void* image);
extern "C" void* WinGraphicsCloneImage(void* image);
extern "C" void WinGraphicsDeleteImage(void* image);
extern "C" uint32_t WinGraphicsImageGetHeight(void* image);
extern "C" uint32_t WinGraphicsImageGetWidth(void* image);
extern "C" void* WinGraphicsCreateBitmap(const char* fileName, bool useEmbeddedColorManagement);
extern "C" void* WinGraphicsCreateBitmapWidthHeight(int w, int h, void* graphics);
extern "C" void* WinGraphicsCreateBitmapWinBitmap(void* winBitmap, void* palette);
extern "C" void* WinGraphicsCreateBitmapIcon(void* icon);
extern "C" void* WinGraphicsCreateBitmapResource(const char* resourceName);
extern "C" void* WinGraphicsCloneBitmap(void* nativeBitmap, int x, int y, int w, int h, int pixelFormat);
extern "C" int WinGraphicsBitmapGetPixel(void* nativeBitmap, int x, int y, uint8_t& alpha, uint8_t& red, uint8_t& green, uint8_t& blue);
extern "C" int WinGraphicsBitmapSetPixel(void* nativeBitmap, int x, int y, uint8_t alpha, uint8_t red, uint8_t green, uint8_t blue);
extern "C" uint32_t WinGraphicsSave(void* graphics);
extern "C" int WinGraphicsRestore(void* graphics, uint32_t graphicsState);
extern "C" void* WinGraphicsCreateDefaultImageAttributes();
extern "C" int WinGraphicsImageAttributesGetLastStatus(void* imageAttributes);
extern "C" void* WinGraphicsCloneImageAttributes(void* imageAttributes);
extern "C" void WinGraphicsDeleteImageAttributes(void* imageAttributes);
extern "C" int WinGraphicsImageAttributesSetColorKey(void* imageAttributes, uint8_t colorLowAlpha, uint8_t colorLowRed, uint8_t colorLowGreen, uint8_t colorLowBlue,
    uint8_t colorHighAlpha, uint8_t colorHighRed, uint8_t colorHighGreen, uint8_t colorHighBlue, int colorAdjustType);
extern "C" int WinGraphicsDrawImagePoint(void* graphics, void* image, float x, float y);
extern "C" int WinGraphicsDrawImageRect(void* graphics, void* image, float x, float y, float w, float h);
extern "C" int WinGraphicsDrawImageWithAttributes(void* graphics, void* image, int destRectX, int destRectY, int destRectW, int destRectH, int srcX, int srcY, int srcW, int srcH,
    int srcUnit, void* imageAttributes);
extern "C" int WinGraphicsDrawImageWithAttributesF(void* graphics, void* image, float destRectX, float destRectY, float destRectW, float destRectH,
    float srcX, float srcY, float srcW, float srcH, int srcUnit, void* imageAttributes);
extern "C" int WinGraphicsGetTransform(void* graphics, void* matrix);
extern "C" int WinGraphicsSetTransform(void* graphics, void* matrix);
extern "C" int WinGraphicsMultiplyTransform(void* graphics, void* matrix, int order);
extern "C" int WinGraphicsResetTransform(void* graphics);
extern "C" int WinGraphicsRotateTransform(void* graphics, float angle, int order);
extern "C" int WinGraphicsScaleTransform(void* graphics, float scaleX, float scaleY, int order);
extern "C" int WinGraphicsTranslateTransform(void* graphics, float offsetX, float offsetY, int order);
extern "C" void* WinGraphicsCreateMatrixFromElements(float m11, float m12, float m21, float m22, float dx, float dy);
extern "C" void* WinGraphicsCreateMatrix();
extern "C" void* WinGraphicsCreateMatrixRectFPointF(float rectX, float rectY, float rectW, float rectH, float ptX, float ptY);
extern "C" void* WinGraphicsCreateMatrixRectPoint(int rectX, int rectY, int rectW, int rectH, int ptX, int ptY);
extern "C" int WinGraphicsMatrixGetLastStatus(void* matrix);
extern "C" void* WinGraphicsCloneMatrix(void* matrix);
extern "C" void WinGraphicsDeleteMatrix(void* matrix);
extern "C" int WinGraphicsMultiplyMatrix(void* matrix, void* factorMatrix, int order);
extern "C" int WinGraphicsResetMatrix(void* matrix);
extern "C" int WinGraphicsInvertMatrix(void* matrix);
extern "C" float WinGraphicsMatrixOffsetX(void* matrix);
extern "C" float WinGraphicsMatrixOffsetY(void* matrix);
extern "C" int WinGraphicsMatrixRotate(void* matrix, float angle, int order);
extern "C" int WinGraphicsMatrixRotateAt(void* matrix, float angle, float centerX, float centerY, int order);
extern "C" int WinGraphicsMatrixScale(void* matrix, float scaleX, float scaleY, int order);
extern "C" int WinGraphicsMatrixSetElements(void* matrix, float m11, float m12, float m21, float m22, float dx, float dy);
extern "C" int WinGraphicsMatrixShear(void* matrix, float shearX, float shearY, int order);
extern "C" int WinGraphicsMatrixTranslate(void* matrix, float offsetX, float offsetY, int order);
extern "C" int WinGraphicsMatrixTransformPoints(void* matrix, void* points, int numPoints);
extern "C" int WinGraphicsMatrixTransformPointsF(void* matrix, void* points, int numPoints);
extern "C" int WinGraphicsGetPageUnit(void* graphics);
extern "C" int WinGraphicsSetPageUnit(void* graphics, int unit);
extern "C" float WinGraphicsGetPageScale(void* graphics);
extern "C" int WinGraphicsSetPageScale(void* graphics, float scale);
extern "C" float WinGraphicsGetDpiX(void* graphics);
extern "C" float WinGraphicsGetDpiY(void* graphics);
extern "C" int WinGraphicsGetSmoothingMode(void* graphics);
extern "C" int WinGraphicsSetSmoothingMode(void* graphics, int smoothingMode);
extern "C" int WinGraphicsGetEncoderClsId(const char* imageFormat, void* clsid);
extern "C" int WinGraphicsImageSave(void* image, const char* fileName, const void* encoderClsId);

#endif // CMRT_WIN_API_INCLUDED
